name: Mobile CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'  

      - name: Install dependencies
        run: flutter pub get

       - name: Decrypt key.properties
        run: |
          openssl enc -d -aes-256-cbc -in key.properties.enc -out key.properties -k "$OPENSSL_PASSWORD"
        env:
          OPENSSL_PASSWORD: ${{ secrets.OPENSSL_PASSWORD }}

      - name: Build release APK
        run: ./gradlew assembleRelease

      - name: Generate signed APK
        run: |
          # Replace with your keystore file handling steps
          echo ${{ secrets.JKS_BASE64 }} | base64 --decode > key.jks
          flutter build apk --release --split-per-abi --build-number=${GITHUB_RUN_NUMBER}

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          files: |
            build/app/outputs/flutter-apk/app-release.apk

      - name: Upload APK to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/app/outputs/flutter-apk/app-release.apk
          asset_name: app-release-${{ github.run_number }}.apk
          asset_content_type: application/vnd.android.package-archive
